// <auto-generated />
namespace EduLiving_Hub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class MigratedModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigratedModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202408092013580_MigratedModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
